// Copyright 2020 Google LLC. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffers for storing active connection information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: github.com/googleinterns/sensor-historian/pb/activeconnection_proto/activeconnection.proto

package activeconnections

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActiveConn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number                 int32  `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	OperatingMode          string `protobuf:"bytes,2,opt,name=OperatingMode,proto3" json:"OperatingMode,omitempty"`
	PackageName            string `protobuf:"bytes,3,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	UID                    int32  `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`
	SensorNumber           int32  `protobuf:"varint,5,opt,name=SensorNumber,proto3" json:"SensorNumber,omitempty"`
	PendingFlush           int32  `protobuf:"varint,6,opt,name=PendingFlush,proto3" json:"PendingFlush,omitempty"`
	SamplingPeriodUs       int32  `protobuf:"varint,7,opt,name=SamplingPeriodUs,proto3" json:"SamplingPeriodUs,omitempty"`
	BatchingPeriodUs       int32  `protobuf:"varint,8,opt,name=BatchingPeriodUs,proto3" json:"BatchingPeriodUs,omitempty"`
	HasSensorserviceRecord bool   `protobuf:"varint,9,opt,name=HasSensorserviceRecord,proto3" json:"HasSensorserviceRecord,omitempty"`
	Source                 string `protobuf:"bytes,10,opt,name=Source,proto3" json:"Source,omitempty"`
}

func (x *ActiveConn) Reset() {
	*x = ActiveConn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveConn) ProtoMessage() {}

func (x *ActiveConn) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveConn.ProtoReflect.Descriptor instead.
func (*ActiveConn) Descriptor() ([]byte, []int) {
	return file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveConn) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ActiveConn) GetOperatingMode() string {
	if x != nil {
		return x.OperatingMode
	}
	return ""
}

func (x *ActiveConn) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ActiveConn) GetUID() int32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *ActiveConn) GetSensorNumber() int32 {
	if x != nil {
		return x.SensorNumber
	}
	return 0
}

func (x *ActiveConn) GetPendingFlush() int32 {
	if x != nil {
		return x.PendingFlush
	}
	return 0
}

func (x *ActiveConn) GetSamplingPeriodUs() int32 {
	if x != nil {
		return x.SamplingPeriodUs
	}
	return 0
}

func (x *ActiveConn) GetBatchingPeriodUs() int32 {
	if x != nil {
		return x.BatchingPeriodUs
	}
	return 0
}

func (x *ActiveConn) GetHasSensorserviceRecord() bool {
	if x != nil {
		return x.HasSensorserviceRecord
	}
	return false
}

func (x *ActiveConn) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto protoreflect.FileDescriptor

var file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDesc = []byte{
	0x0a, 0x5a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x2d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xee,
	0x02, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12,
	0x22, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x6c,
	0x75, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x10, 0x53, 0x61, 0x6d, 0x70, 0x6c,
	0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x55, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x55, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x55, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x55, 0x73, 0x12,
	0x36, 0x0a, 0x16, 0x48, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x16, 0x48, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42,
	0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2f, 0x73, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x2d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6e, 0x2f, 0x70, 0x62, 0x2f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescOnce sync.Once
	file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescData = file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDesc
)

func file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescGZIP() []byte {
	file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescOnce.Do(func() {
		file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescData)
	})
	return file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDescData
}

var file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_goTypes = []interface{}{
	(*ActiveConn)(nil), // 0: activeconnection.ActiveConn
}
var file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_init()
}
func file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_init() {
	if File_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveConn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_goTypes,
		DependencyIndexes: file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_depIdxs,
		MessageInfos:      file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_msgTypes,
	}.Build()
	File_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto = out.File
	file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_rawDesc = nil
	file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_goTypes = nil
	file_github_com_googleinterns_sensor_historian_pb_activeconnection_proto_activeconnection_proto_depIdxs = nil
}
